// Angular/ng7/src/app/nav/nav.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-nav',
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.scss']
})
export class NavComponent implements OnInit {
  appTitle: string = 'myApp'
  constructor() { }

  ngOnInit() {
  }

}

<header>
<div class="container">
    <a routerLink="/" class="logo">{{appTitle}}</a>

    <nav>
        <ul>
            <li><a routerLink="/">Home</a></li>
            <li><a routerLink="/about">About</a></li>
            <li><a routerLink="/contact">Contact</a></li>
        </ul>
    </nav>
</div>
</header>

// REACT/myreact/src/components/nav/Nav.js
import React from 'react';
import './Nav.scss';

function Nav() {
  let appTitle = "My App"
  return (
      <header  className="Nav">
        <div class="container">
          <a  class="logo">{appTitle}</a>
          <nav>
            <ul>
              <li><a >Home</a></li>
              <li><a >About</a></li>
              <li><a >Contact</a></li>
            </ul>
          </nav>
        </div>
      </header>
  );
}

export default Nav;
